src/App/ViewModels/ProdutoViewModel.cs
using App.Extensions;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace App.ViewModels;

public class ProdutoViewModel
{
    [Key]
    public Guid Id { get; set; }

    [Required(ErrorMessage = "O Campo {0} é obrigatorio")]
    [DisplayName("Fornecedor")]
    public Guid FornecedorId { get; set; }

    [Required(ErrorMessage = "O Campo {0} é obrigatorio")]
    [StringLength(200, ErrorMessage = "O Campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
    public string Nome { get; set; }

    [DisplayName("Descrição")]
    [Required(ErrorMessage = "O Campo {0} é obrigatorio")]
    [StringLength(1000, ErrorMessage = "O Campo {0} precisa ter entre {2} e {1} caracteres", MinimumLength = 2)]
    public string Descricao { get; set; }

    [DisplayName("Imagem do Produto")]
    public IFormFile? ImagemUpload { get; set; }
    public string? Imagem { get; set; }

    [Moeda]
    [Required(ErrorMessage = "O Campo {0} é obrigatorio")]
    public decimal Valor { get; set; }

    [ScaffoldColumn(false)]
    public DateTime DataCadastro { get; set; }

    [DisplayName("Ativo?")]
    public bool Ativo { get; set; }

    public FornecedorViewModel? Fornecedor { get; set; }

    public IEnumerable<FornecedorViewModel>? Fornecedores { get; set; }
}

src/App/Controllers/ProdutosController.cs
using App.Extensions;
using App.ViewModels;
using AutoMapper;
using Business.Interfaces;
using Business.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace App.Controllers;

[Authorize]
public class ProdutosController : BaseController
{
	private readonly IProdutoRepository _produtoRepository;
	private readonly IProdutoService _produtoService;
	private readonly IFornecedorRepository _fornecedorRepository;
	private readonly IMapper _mapper;

	public ProdutosController(IProdutoRepository produtoRepository,
							  IFornecedorRepository fornecedorRepository,
							  IMapper mapper,
							  IProdutoService produtoService,
							  INotificador notificador) : base(notificador)
	{
		_produtoRepository = produtoRepository;
		_fornecedorRepository = fornecedorRepository;
		_mapper = mapper;
		_produtoService = produtoService;
	}

	// Método que retorna uma View com uma lista de produtos com seus devidos fornecedores
	[Route("lista-de-produtos")]
	[AllowAnonymous]
	public async Task<IActionResult> Index()
	{
		return View(_mapper.Map<IEnumerable<ProdutoViewModel>>(await _produtoRepository.ObterProdutosFornecedores()));
	}

	// Retorna 1 produto com seu devido fornecedor
	[Route("dados-do-produto/{id:guid}")]
	[AllowAnonymous]
	public async Task<IActionResult> Details(Guid id)
	{
		var produtoViewModel = await ObterProduto(id);

		if (produtoViewModel == null) return NotFound();

		return View(produtoViewModel);
	}

	[Route("novo-produto")]
	[ClaimsAuthorize("Produto", "Adicionar")]
	public async Task<IActionResult> Create()
	{
		var produtoViewModel = await PopularFornecedores(new ProdutoViewModel());
		return View(produtoViewModel);
	}

	[HttpPost]
	[Route("novo-produto")]
	[ClaimsAuthorize("Produto", "Adicionar")]
	public async Task<IActionResult> Create(ProdutoViewModel produtoViewModel)
	{
		produtoViewModel = await PopularFornecedores(produtoViewModel);
		if (!ModelState.IsValid) return View(produtoViewModel);

		var imgPrefixo = Guid.NewGuid() + "_";
		if (!await UploadArquivo(produtoViewModel.ImagemUpload, imgPrefixo))
		{
			return View(produtoViewModel);
		}

		produtoViewModel.Imagem = imgPrefixo + produtoViewModel.ImagemUpload.FileName;

		await _produtoService.Adicionar(_mapper.Map<Produto>(produtoViewModel));

		if (!OperacaoValida()) return View(produtoViewModel);

		return RedirectToAction("Index");
	}

	[Route("editar-produto/{id:guid}")]
	[ClaimsAuthorize("Produto", "Editar")]
	public async Task<IActionResult> Edit(Guid id)
	{
		var produtoViewModel = await ObterProduto(id);

		if (produtoViewModel == null) return NotFound();

		return View(produtoViewModel);
	}

	[HttpPost]
	[Route("editar-produto/{id:guid}")]
	[ClaimsAuthorize("Produto", "Editar")]
	public async Task<IActionResult> Edit(Guid id, ProdutoViewModel produtoViewModel)
	{
		if (id != produtoViewModel.Id) return NotFound();

		var produtoAtualizacao = await ObterProduto(id);
		produtoViewModel.Fornecedor = produtoAtualizacao.Fornecedor;
		produtoViewModel.Imagem = produtoAtualizacao.Imagem;
		if (!ModelState.IsValid) return View(produtoViewModel);

		if (produtoViewModel.ImagemUpload != null)
		{
			var imgPrefixo = Guid.NewGuid() + "_";
			if (!await UploadArquivo(produtoViewModel.ImagemUpload, imgPrefixo))
			{
				return View(produtoViewModel);
			}

			produtoAtualizacao.Imagem = imgPrefixo + produtoViewModel.ImagemUpload.FileName;
		}

		produtoAtualizacao.Nome = produtoViewModel.Nome;
		produtoAtualizacao.Descricao = produtoViewModel.Descricao;
		produtoAtualizacao.Valor = produtoViewModel.Valor;
		produtoAtualizacao.Ativo = produtoViewModel.Ativo;

		await _produtoService.Atualizar(_mapper.Map<Produto>(produtoAtualizacao));

		if (!OperacaoValida()) return View(produtoViewModel);

		return RedirectToAction("Index");
	}

	[Route("excluir-produto/{id:guid}")]
	[ClaimsAuthorize("Produto", "Excluir")]
	public async Task<IActionResult> Delete(Guid id)
	{
		var produto = await ObterProduto(id);

		if (produto == null) return NotFound();

		return View(produto);
	}

	[HttpPost, ActionName("Delete")]
	[Route("excluir-produto/{id:guid}")]
	[ClaimsAuthorize("Produto", "Excluir")]
	public async Task<IActionResult> DeleteConfirmed(Guid id)
	{
		var produto = await ObterProduto(id);
		if (produto == null) return NotFound();

		await _produtoService.Remover(id);

		if (!OperacaoValida()) return View(produto);

        /* Note que quando a operação é um sucesso nós redirecionamos para a action
		 * de Index, ou seja, para que nossa notificação apareça para o usuário em caso
		 * de sucesso precisamos declarar a mensagem dentro de um TempData, pois só ele
		 * sobrevive a um redirecionamento, ao contrario de uma ViewBag. Para entender melhor
		 * veja o arquivo Views/Shared/Components/Summary/Default.cshtml. */
        TempData["Sucesso"] = "Produto excluido com sucesso!";

		return RedirectToAction("Index");
	}

	private async Task<ProdutoViewModel> ObterProduto(Guid id)
	{
		var produto = _mapper.Map<ProdutoViewModel>(await _produtoRepository.ObterProdutoFornecedor(id));

		// Popula a lista de fornecedores
		produto.Fornecedores = _mapper.Map<IEnumerable<FornecedorViewModel>>(await _fornecedorRepository.ObterTodos());

		return produto;
	}

	// A partir de qualquer viewModel que você passe, popula os fornecedores da viewModel
	private async Task<ProdutoViewModel> PopularFornecedores(ProdutoViewModel produto)
	{
		produto.Fornecedores = _mapper.Map<IEnumerable<FornecedorViewModel>>(await _fornecedorRepository.ObterTodos());
		return produto;
	}

	private async Task<bool> UploadArquivo(IFormFile arquivo, string imgPrefixo)
	{
		if (arquivo.Length <= 0) return false;

		var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/imagens", imgPrefixo + arquivo.FileName);

		if (System.IO.File.Exists(path))
		{
			ModelState.AddModelError(string.Empty, "Já existe um arquivo com este nome!");
			return false;
		}

		using (var stream = new FileStream(path, FileMode.Create))
		{
			await arquivo.CopyToAsync(stream);
		}

		return true;
	}
}

src/App/Extensions/SummaryViewComponent.cs
using Business.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace App.Extensions;

// Classe que resume os erros e os exibe na view diretamente
public class SummaryViewComponent : ViewComponent
{
	private readonly INotificador _notificador;

	public SummaryViewComponent(INotificador notificador)
	{
		_notificador = notificador;
	}

	/* Por herdar de ViewComponent podemos chamar este metodo, que executa uma tarefa de forma assincrona,
	 * vamos utiliza-lo para retornar a View Deafult que está declarada em Views/Shared/Components/Summary/Default.cshtml
	 * Note que este é o nome padrão para este tipo de View, e que o caminho também é um caminho padrão para declarar
	 * este tipo de ViewComponent */
	public async Task<IViewComponentResult> InvokeAsync()
	{
		/* Como o metodo ObterNotificacoes não é assincrono, e estamos dentro de um contexto assincrono, precisamos utilizar
		 * o await Task.FromResult() e o método que precisamos do resultado. */
		var notificacoes = await Task.FromResult(_notificador.ObterNotificacoes());

		/* Para cada notificação vamos adicionar dentro da ModelState um ModelError, cujo a chave vai ser vazia e o valor
		 * vai ser a mensagem de erro, assim podemos declarar a ModelState como invalida caso algum erro ocorra, e vamos
		 * compreender como um erro de preeenchimento de campo, só que sem um campo especifico. */
		notificacoes.ForEach(n => ViewData.ModelState.AddModelError(string.Empty, n.Mensagem));

		return View();
	}
}

src/App/Views/Produtos/Create.cshtml
@model App.ViewModels.ProdutoViewModel

@{
    ViewData["Title"] = "Novo Produto";
}

<h3 style="padding-top: 50px">@ViewData["Title"]</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <vc:summary></vc:summary>
            <div class="form-group">
                <label asp-for="FornecedorId" class="control-label"></label>
                <select asp-for="FornecedorId" class="form-control dropdown-header" asp-items="@(new SelectList(Model.Fornecedores, "Id", "Nome"))">
                    <option></option>
                </select>
                <span asp-validation-for="FornecedorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <textarea cols="40" rows="5" asp-for="Descricao" class="form-control"></textarea>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagemUpload" class="control-label"></label>
                
                <div class="custom-file">
                    <input type="file" class="form-control" id="ImagemUpload" asp-for="ImagemUpload" multiple/>
                    <label data-browse="Procurar" style="width: 400px" class="custom-file-label" for="ImagemUpload"></label>
                    <label style="display: none" id="img_nome"></label>
                </div>

                <span asp-validation-for="ImagemUpload" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a class="btn btn-info" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $("#ImagemUpload").change(function(){
            $("#img_nome").text(this.files[0].name);
            $("#img_nome")[0].style.display = 'block';
        });

        $("#ImagemUpload").attr("data-val", "true");
        $("#ImagemUpload").attr("data-val-required", "Preencha o campo imagem!");
    </script>
}

src/App/Views/Produtos/Delete.cshtml
@model App.ViewModels.ProdutoViewModel

@{
	ViewData["Title"] = "Excluir " + Model.Nome;
}

<h4 style="padding-top: 50px;">@ViewData["Title"]</h4>
<h5>Você tem certeza disso?</h5>
<div class="row">
	<div class="col-md-4">
		<img src="~/imagens/@Model.Imagem" alt="@Model.Imagem" style="max-width: 340px; max-height: 340px; width: 100%;" />
	</div>
	<div class="col-md-6">
		<dl>
			<dt>
				@Html.DisplayNameFor(model => model.FornecedorId)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Fornecedor.Nome)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.Nome)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Nome)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.Descricao)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Descricao)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.Valor)
			</dt>
			<dd>
				@Model.Valor.ToString("C")
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.DataCadastro)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.DataCadastro)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.Ativo)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Ativo)
			</dd>
		</dl>
		<div>
			<form asp-action="Delete">
				<input type="hidden" asp-for="Id" />
				<input type="submit" value="Excluir" class="btn btn-danger" />
				<a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
			</form>
		</div>
	</div>
</div>

src/App/Views/Produtos/Details.cshtml
@model App.ViewModels.ProdutoViewModel

@{
	ViewData["Title"] = "Detalhe do Produto " + Model.Nome;
}

<h4 style="padding-top: 50px;">@ViewData["Title"]</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<img src="~/imagens/@Model.Imagem" alt="@Model.Imagem" style="max-width: 340px; max-height: 340px; width: 100%;" />
	</div>
	<div class="col-md-6">
		<dl>
			<dt>
				@Html.DisplayNameFor(model => model.FornecedorId)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Fornecedor.Nome)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.Nome)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Nome)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.Descricao)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Descricao)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.Valor)
			</dt>
			<dd>
				@Model.Valor.ToString("C")
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.DataCadastro)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.DataCadastro)
			</dd>
			<dt>
				@Html.DisplayNameFor(model => model.Ativo)
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Ativo)
			</dd>
		</dl>
	</div>
</div>
<div>
	<a class="btn btn-dark" asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
	<a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
</div>

src/App/Views/Produtos/Edit.cshtml
@model App.ViewModels.ProdutoViewModel

@{
	ViewData["Title"] = "Editar " + Model.Nome;
}

<h4 style="padding-top: 30px">@ViewData["Title"]</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form enctype="multipart/form-data" asp-action="Edit">
			<vc:summary></vc:summary>

			<input type="hidden" asp-for="Id" />

			<div class="form-group">
				<label asp-for="FornecedorId" class="control-label"></label><br />
				<label><b>@Model.Fornecedor.Nome</b></label>

			</div>

			<div class="form-group">
				<label asp-for="Nome" class="control-label"></label>
				<input asp-for="Nome" class="form-control" />
				<span asp-validation-for="Nome" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Descricao" class="control-label"></label>
				<textarea cols="40" rows="5" asp-for="Descricao" class="form-control"></textarea>
				<span asp-validation-for="Descricao" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label>Imagem Atual</label><br />
				<img src="~/imagens/@Model.Imagem" alt="@Model.Imagem" style="max-width: 100px; max-height: 100px;" />
			</div>
			<div class="form-group">
				<label asp-for="ImagemUpload" class="control-label"></label>
				<div class="custom-file">
					<input type="file" class="form-control" id="ImagemUpload" asp-for="ImagemUpload" multiple />
					<label data-browse="Procurar" style="width: 400px" class="custom-file-label" for="ImagemUpload"></label>
					<label style="display: none" id="img_nome"></label>
				</div>
				<span asp-validation-for="ImagemUpload" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="Valor" class="control-label"></label>
				<input asp-for="Valor" class="form-control" />
				<span asp-validation-for="Valor" class="text-danger"></span>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					<input class="form-check-input" asp-for="Ativo" /> @Html.DisplayNameFor(model => model.Ativo)
				</label>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
				<a class="btn btn-info" href="javascript:window.history.back();">Voltar</a>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
	<script>
		$("#ImagemUpload").change(function () {
			$("#img_nome").text(this.files[0].name);
			$("#img_nome")[0].style.display = 'block';
		});
	</script>
}

src/App/Views/Produtos/Index.cshtml
@model IEnumerable<App.ViewModels.ProdutoViewModel>

@{
	ViewData["Title"] = "Lista de Produtos";
}

<h1>@ViewData["Title"]</h1>
<hr />
<vc:summary></vc:summary>
<p>
	<a class="btn btn-info" asp-action="Create">Adicionar Produto</a>
</p>
<partial name="_ListaProdutos"></partial>

src/App/Views/Produtos/_ListaProdutos.cshtml
@model IEnumerable<App.ViewModels.ProdutoViewModel>

<table class="table table-hover">
	<thead class="table-dark">
		<tr>
			<th>

			</th>
			<th>
				@Html.DisplayNameFor(model => model.Nome)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Fornecedor)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Valor)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Ativo)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					<img src="~/imagens/@item.Imagem" alt="@item.Imagem" style="max-width: 100px; max-height: 100px;" />
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Nome)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Fornecedor.Nome)
				</td>
				<td>
					@* Converte o valor em string com o formato de Currency por conta do parâmetro ("C") *@
					@item.Valor.ToString("C")
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Ativo)
				</td>
				<td class="text-right">
					<a class="btn btn-info" asp-controller="Produtos" asp-action="Details" asp-route-id="@item.Id"><span class="fa fa-search"></span></a>
					<a class="btn btn-warning" asp-controller="Produtos" asp-action="Edit" asp-route-id="@item.Id"><span class="fa fa-pencil-alt"></span></a>
					<a class="btn btn-danger" asp-controller="Produtos" asp-action="Delete" asp-route-id="@item.Id"><span class="fa fa-trash-can"></span></a>
				</td>
			</tr>
		}
	</tbody>
</table>